=== Bibliothek-der-Neologie/bdnBible/data/units.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="unit">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:integer" name="from-verse"/>
          <xs:attribute type="xs:integer" name="to-verse"/>
          <xs:attribute type="xs:integer" name="from-chapter"/>
          <xs:attribute type="xs:integer" name="to-chapter"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="chapter">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="unit" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:integer" name="n"/>
      <xs:attribute type="xs:integer" name="from-chapter" use="optional"/>
      <xs:attribute type="xs:integer" name="from-verse"/>
      <xs:attribute type="xs:integer" name="to-chapter" use="optional"/>
      <xs:attribute type="xs:integer" name="to-verse"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="book">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <xs:element ref="unit"/>
        <xs:element ref="chapter"/>
      </xs:choice>
      <xs:attribute type="xs:string" name="name" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="units">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="book" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Bibliothek-der-Neologie/bdnBible/data/units.xml
<?xml version='1.0' encoding='utf-8'?>
<units xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="units.xsd">
  <book name="Gen">
    <unit from-chapter="1" from-verse="1" to-chapter="2" to-verse="4">Priesterlicher Schöpfungsbericht</unit>
    <unit from-chapter="2" from-verse="4" to-chapter="3" to-verse="24">Nichtpriesterschriftlicher Schöpfungsbericht</unit>
    <chapter n="11">
    <unit from-verse="1" to-verse="9">Der Turmbau zu Babel</unit>
    </chapter>
    <chapter n="12">
    <unit from-verse="1" to-verse="9">Abrams Berufung</unit>
    </chapter>
    <chapter n="17">
    <unit from-verse="1" to-verse="27">Der ewige Bund mit Abraham</unit>
    </chapter>
    <chapter n="18">
    <unit from-verse="1" to-verse="15">Der Herr bei Abraham und Sara in Mamre</unit>
    <unit from-verse="16" to-verse="33">Abrahams Fürbitte für Sodom</unit>
    </chapter>
    <chapter n="22">
    <unit from-verse="1" to-verse="19">Das Opfer Abrahams / Bindung Isaaks</unit>
    </chapter>
    <chapter n="28">
    <unit from-verse="10" to-verse="22">Jakob schaut die Himmelsleiter</unit>
    </chapter>
    <chapter n="32">
    <unit from-verse="23" to-verse="33">Jakobs Kampf am Jabbok</unit>
    </chapter>
    <unit from-chapter="37" from-verse="1" to-chapter="50" to-verse="26">Josefs-Novelle<!-- kann man Kapitel 38 aussparen? -->
</unit>  
  </book>
  <book name="Ex">
    <unit from-chapter="3" from-verse="1" to-chapter="4" to-verse="17">Moses Berufung</unit>
    <chapter n="3">
      <unit verse="14">Offenbarung des Gottesnamens (JHWH)<!-- Einzelvers? -->
</unit>
    </chapter>
    <chapter n="20">
      <unit from-verse="1" to-verse="17">Dekalog</unit>
    </chapter>
  </book>
  <book name="Num">
    <unit from-chapter="7" from-verse="1" to-chapter="9" to-verse="14">Letzte kultische Handlungen und Anweisungen am Sinai</unit>
  </book>
  <book name="Dtn">
    <chapter n="6">
      <unit from-verse="4" to-verse="6">Schema Jisrael</unit>
    </chapter>
  </book>
  <book name="Jes">
    <chapter n="42">
      <unit from-verse="1" to-verse="4">Erstes Gottesknechtslied</unit>
    </chapter>
    <chapter n="49">
      <unit from-verse="1" to-verse="6">Zweites Gottesknechtslied</unit>
    </chapter>
    <chapter n="50">
      <unit from-verse="4" to-verse="9">Drittes Gottesknechtslied</unit>
    </chapter>
    <unit from-chapter="52" from-verse="13" to-chapter="53" to-verse="12">Viertes Gottesknechtslied</unit>
  </book>
  <book name="Mt">
    <unit from-chapter="1" from-verse="1" to-chapter="4" to-verse="22">Vorgeschichte</unit>
    <chapter n="1">
      <unit from-verse="1" to-verse="25">Herkunft Jesu ("Urkunde des Ursprungs")</unit>
      <unit from-verse="18" to-verse="25">Jesu Geburt</unit>
    </chapter>
    <chapter n="2">
      <unit from-verse="1" to-verse="12">Die Weisen aus dem Morgenland</unit>
      <unit from-verse="13" to-verse="15">Die Flucht nach Ägypten</unit>
    </chapter>
    <chapter n="3">
      <unit from-verse="1" to-verse="17">Auftreten des Täufers und Taufe Jesu</unit>
      <unit from-verse="1" to-verse="12">Johannes der Täufer</unit>
      <unit from-verse="13" to-verse="17">Jesu Taufe</unit>
    </chapter>
    <unit from-chapter="4" from-verse="23" to-chapter="9" to-verse="35">Jesus als der Messias des Wortes und der Tat</unit>
    <chapter n="4">
      <unit from-verse="1" to-verse="11">Jesu Versuchung ("Versuchungsgeschichte")</unit>
      <unit from-verse="12" to-verse="22">Beginn der Wirksamkeit Jesu</unit>
      <unit from-verse="12" to-verse="17">Der Beginn des Wirkens Jesu in Galiläa</unit>
      <unit from-verse="23" to-verse="25">Summarium I</unit>
    </chapter>
    <unit from-chapter="5" from-verse="1" to-chapter="7" to-verse="29">Bergpredigt<!-- wird gängig auch bis 8,1 gezogen -->
</unit>
    <chapter n="5">
      <unit from-verse="1" to-verse="12">Die Seligpreisungen</unit>
      <unit from-verse="13" to-verse="16">Salz und Licht</unit>
      <unit from-verse="17" to-verse="20">Jesu Stellung zum Gesetz</unit>
      <unit from-verse="21" to-verse="26">Vom Töten</unit>
      <unit from-verse="27" to-verse="32">Vom Ehebrechen</unit>
      <unit from-verse="33" to-verse="37">Vom Schwören</unit>
      <unit from-verse="38" to-verse="42">Vom Vergelten</unit>
      <unit from-verse="43" to-verse="48">Von der Feindesliebe</unit>
    </chapter>
    <chapter n="6">
      <unit from-verse="1" to-verse="4">Vom Almosengeben</unit>
      <unit from-verse="5" to-verse="15">Vom Beten (Vaterunser)</unit>
      <unit from-verse="16" to-verse="18">Vom Fasten</unit>
      <unit from-verse="19" to-verse="34">Vom Schätzesammeln und Sorgen</unit>
    </chapter>
    <chapter n="7">
      <unit from-verse="7" to-verse="11">Von der Zuversicht beim Beten</unit>
      <unit from-verse="12" to-verse="14">Die Goldene Regel. Von den zwei Wegen</unit>
      <unit from-verse="15" to-verse="23">Warnung vor den falschen Propheten</unit>
      <unit from-verse="24" to-verse="29">Vom Hausbau</unit>
    </chapter>
    <unit from-chapter="8" from-verse="1" to-chapter="9" to-verse="34">Die Taten Jesu als Ausweis seiner Vollmacht</unit>
    <chapter n="8">
      <unit from-verse="5" to-verse="13">Der Hauptmann von Kapernaum</unit>
      <unit from-verse="18" to-verse="22">Vom Ernst der Nachfolge</unit>
      <unit from-verse="28" to-verse="34">Die Heilung von zwei besessenen Gadarenern</unit>
    </chapter>
    <unit from-chapter="9" from-verse="36" to-chapter="11" to-verse="1">Aussendung der Jünger</unit>
    <chapter n="9">
      <unit from-verse="1" to-verse="8">Die Heilung eines Gelähmten</unit>
      <unit from-verse="35" to-verse="35">Summarium II</unit>
      <unit from-verse="36" to-verse="38">Jesu Erbarmen über das Volk</unit>
    </chapter>
    <unit from-chapter="10" from-verse="5" to-chapter="11" to-verse="1">Aussendungsrede</unit>
    <chapter n="10">
      <unit from-verse="1" to-verse="1">Vollmacht für die Jünger</unit>
      <unit from-verse="2" to-verse="4">Jüngerliste</unit>
      <unit from-verse="16" to-verse="26">Die Ansage kommender Verfolgungen</unit>
      <unit from-verse="40" to-verse="42">Aufnahme um Jesu willen</unit>
    </chapter>
    <unit from-chapter="11" from-verse="2" to-chapter="16" to-verse="20">Das Entstehen der Gemeinde in der Auseinandersetzung um das Wesen Jesu</unit>
    <chapter n="11">
      <unit from-verse="2" to-verse="24">Anfrage des Täufers und Antwort Jesu</unit>
      <unit from-verse="25" to-verse="30">Jesu Lobpreis ("Werberede"). Der Heilandsruf</unit>
    </chapter>
    <chapter n="12">
      <unit from-verse="1" to-verse="50">Die Lehre Jesu im Widerstreit</unit>
      <unit from-verse="38" to-verse="45">Die Zeichenforderung der Pharisäer</unit>
    </chapter>
    <unit from-chapter="13" from-verse="53" to-chapter="14" to-verse="36">Jesus zwischen Ablehnung in der Vaterstadt und Glauben der Jünger</unit>
    <chapter n="13">
      <unit from-verse="1" to-verse="52">Gleichnisrede</unit>
      <unit from-verse="10" to-verse="17">Vom Sinn der Gleichnisse</unit>
    </chapter>
    <unit from-chapter="15" from-verse="1" to-chapter="16" to-verse="12">Auseinandersetzung um die Reinheitsgebote, Wunder und Warnung vor Pharisäern,Sadduzäern</unit>
    <chapter n="16">
      <unit from-verse="13" to-verse="20">Petrusbekenntnis in Caesarea Philippi</unit>
      <unit from-verse="21" to-verse="28">1. Leidensankündigung und Nachfolgeworte</unit>
    </chapter>
    <chapter n="17">
      <unit from-verse="1" to-verse="13">Verklärungsgeschichte</unit>
      <unit from-verse="14" to-verse="27">Kraft des Glaubens, 2. Leidensankündigung, Tempelsteuer</unit>
    </chapter>
    <chapter n="18">
      <unit from-verse="1" to-verse="35">"Gemeinderegel"</unit>
    </chapter>
    <unit from-chapter="19" from-verse="1" to-chapter="20" to-verse="16">Aufbruch nach Jerusalem, Zugang zum Himmelreich</unit>
    <chapter n="20">
      <unit from-verse="17" to-verse="34">3. Leidensankündigung, Abschluß der Jüngerbelehrung</unit>
    </chapter>
    <unit from-chapter="21" from-verse="1" to-chapter="25" to-verse="46">Wirksamkeit Jesu in Jerusalem</unit>
    <unit from-chapter="21" from-verse="23" to-chapter="22" to-verse="14">Frage nach der Vollmacht Jesu</unit>
    <chapter n="21">
      <unit from-verse="1" to-verse="17">Einzug in Jerusalem und Tempelreinigung</unit>
      <unit from-verse="18" to-verse="22">Die Macht des Glaubens</unit>
    </chapter>
    <chapter n="22">
      <unit from-verse="15" to-verse="46">Jesus als Lehrer im Tempel</unit>
    </chapter>
    <chapter n="23">
      <unit from-verse="1" to-verse="39">Antipharisäische Rede</unit>
    </chapter>
    <unit from-chapter="24" from-verse="1" to-chapter="25" to-verse="46">Ankündigung der Zerstörung des Tempels und Rede von den letzten Dingen</unit>
    <unit from-chapter="26" from-verse="1" to-chapter="27" to-verse="66">Passionsgeschichte</unit>
    <unit from-chapter="26" from-verse="57" to-chapter="27" to-verse="2">Verhandlung / Todesurteil des Synedriums</unit>
    <chapter n="26">
      <unit from-verse="1" to-verse="5">Letzte Leidensankündigung; Todesbeschluß</unit>
      <unit from-verse="6" to-verse="16">Salbung in Betanien; Verrat des Judas Iskariot</unit>
      <unit from-verse="17" to-verse="35">Letztes Mahl Jesu mit den Jüngern; Ansage ihrer Flucht</unit>
      <unit from-verse="26" to-verse="28">Abendmahlsworte</unit>
      <unit from-verse="36" to-verse="56">Getsemani Gefangennahme Jesu und Flucht der Jünger</unit>
    </chapter>
    <chapter n="27">
      <unit from-verse="3" to-verse="10">Reue und Selbstmord des Judas</unit>
      <unit from-verse="11" to-verse="26">Verhandlung vor Pilatus</unit>
      <unit from-verse="27" to-verse="56">Verspottung durch die Soldaten; Kreuzigung</unit>
      <unit from-verse="57" to-verse="61">Grablegung</unit>
      <unit from-verse="62" to-verse="66">Die Wache vor dem Grab</unit>
    </chapter>
